server:
  port: 9001

#Eureka Configuration Properties  
eureka: 
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

mildap:
  url: ldap://localhost:389/dc=abundio,dc=com
ldap:
  url: ldap:/localhost:389
spring:
  datasource:
    url:jdbc:postgresql://localhost3:5432/Invest

