server:
  port: 8080

spring:
  application:
    name: zuul-server

#Zuul Configuration Properties
zuul:
  routes:
       ech-svc:
        path: /echo/**
        serviceId: echo-service
       refresh-svc:
        path: /testldap/**
        serviceId: refresh-service
       appvis-svc:
        path: /app/**
        url: http://localhost:9001
       restapi-svc:
        path: /restapi/**
        url: http://localhost:9002

#Eureka Configuration Properties
eureka: 
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
