server:
  port: 8080

spring:
  application:
    name: zuul-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    appname: zuul-server
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}

#zuul:
#  routes:
#    echo:
#      path: /echo/**
#      serviceId: echo-service

zuul:
  routes:
    echo-service:
      path: /echo/**
      serviceId: echo-service
ribbon:
  eureka:
    enabled: false

echo-service:
  ribbon:
    listOfServers: http://eureka-server:8091,http://eureka-server:8092
