server:
  port: 8080

spring:
  application:
    name: zuul-server

#Zuul Configuration Properties
zuul:
  routes:
      pldap-service:
        path: /testldap/**
        serviceId: ldapservice-service
 
#Eureka Configuration Properties
eureka: 
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
