server:
  port: 8080

spring:
  application:
    name: zuul-server

#Zuul Configuration Properties
zuul:
  routes:
       ech-svc:
        path: /echo/**
        serviceId: echo-service
       pldap-service:
        path: /testldap/**
        url: http://localhost:7094

#Eureka Configuration Properties
eureka: 
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
