# HTTP Server
server:
  port: 8888

  #management:
    #endpoint:
    #health:
    #show-details=always
    #sensitive = false
      #web:
      #exposure:
    #include = *

spring:
  # Spring Cloud Config Server Repository
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Abundios/SpringCloudConfig-GitRepository
          #timeout: 20
          #skipSslValidation: true




  # Spring properties
    #profiles:
    #  active: dev
